# Generated by Django 4.1.3 on 2022-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=10)),
                ('identity_qu', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
