# Generated by Django 4.1.3 on 2022-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
